### ISSUE TITLE
Compiling error on MacOS version 12.4 

### ISSUE THREAD

**Issue by mhmughees** [sga001/sealpir-rust#1]
**My eventual goal is to compile [mpir](https://github.com/sga001/mpir)

But as this is a dependency so I need to compile this first. I did the steps mentioned in the repo ,  I am on rustc version 1.30.0
But when I do cargo build** 

Compilation field with very long error output, I am pasting some of it below

error[E0433]: failed to resolve. Use of undeclared type or module `proc_macro`
  --> /Users/haris-imac/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/detection.rs:67:37
   |
67 |     let works = panic::catch_unwind(proc_macro::Span::call_site).is_ok();
   |                                     ^^^^^^^^^^ Use of undeclared type or module `proc_macro`

error[E0433]: failed to resolve. Use of undeclared type or module `proc_macro`
   --> /Users/haris-imac/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/fallback.rs:228:11
    |
228 | impl From<proc_macro::TokenStream> for TokenStream {
    |           ^^^^^^^^^^ Use of undeclared type or module `proc_macro`

error[E0433]: failed to resolve. Use of undeclared type or module `proc_macro`
   --> /Users/haris-imac/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/fallback.rs:229:20
    |
229 |     fn from(inner: proc_macro::TokenStream) -> TokenStream {
    |                    ^^^^^^^^^^ Use of undeclared type or module `proc_macro`

error[E0433]: failed to resolve. Use of undeclared type or module `proc_macro`
   --> /Users/haris-imac/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/fallback.rs:238:28
    |
238 | impl From<TokenStream> for proc_macro::TokenStream {
    |                            ^^^^^^^^^^ Use of undeclared type or module `proc_macro`

**Any idea on how to fix it?**

**Comment by sga001** [comment]
Yeah, so this problem is way outside of this codebase. It is one of the dependencies that didn't respect versioning and kept making changes that no longer work with this compiler :(. 

I think at this point there are 2 things I'd rather do than trying to fix this: 

(1) Use Tancrede's SealPIR implementation: https://github.com/tlepoint/fhe.rs/tree/main/crates/fhe/examples, and then port MPIR to use that.

(2) Write an MPIR version in C++.

**Comment by mhmughees** [comment]
yeah I think I will soon work on porting this to Tancrede's library. I am inclined towards moving everything to rust, thinking to port OnionPIR to rust as well. 

Btw thanks for providing codebase with every project. Very inspiring, trying to follow that :)

**Comment by sga001** [comment]
If you want, we can work on porting mpir to use Tencrede's version together. That's probably the easiest thing rather than using FFI to interface between Rust and C++. I don't know what I was thinking.

**Comment by sga001** [comment]
The latest version which I just pushed should compile now.
It works for me with rustc 1.63 and gcc/g++ 11.3.

**Comment by sga001** [comment]
I also fixed mpir in case you still need it.
